gewe:
  base-url: http://116.198.233.110:2531
  prefix: /v2/api/

llm:
  glm:
    token: 33ba0ccafc6527f76f9798f71ed2f488.cDIXhvPrfxn75dy8
    base-url: https://open.bigmodel.cn/api/paas/v4/
    models:
      text: GLM_4_FLASH
      image-understanding: GLM_4V_FLASH
      image-generation: COGVIEW_3_FLASH