gewe:
  #gewe 接口地址
  base-url: #########################
  prefix: /v2/api/
# llm
llm:
  glm:
    token: ##########################
    base-url: https://open.bigmodel.cn/api/paas/v4/
# mongo-plus
mongo-plus:
  data:
    mongodb:
      host: #####   #ip
      port: 27017   #端口
      database: database    #数据库名
      username: username    #用户名，没有可不填（若账号中出现@,!等等符号，不需要再进行转码！！！）
      password: password    #密码，同上（若密码中出现@,!等等符号，不需要再进行转码！！！）
      authenticationDatabase: wechat     #验证数据库
      connectTimeoutMS: 50000   #在超时之前等待连接打开的最长时间（以毫秒为单位）

coze:
  token: ###########


